spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        group: DEFAULT_GROUP
        namespace: idlestore-prod
        server-addr: 127.0.0.1:8848
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        server-addr: 127.0.0.1:8848
        namespace: idlestore-prod

  config:
    import:
      - nacos:shared-redis.yaml?group=DEFAULT_GROUP&refreshEnabled=true