<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lh</groupId>
        <artifactId>idle-store</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>idle-store-user</artifactId>
    <!-- 多模块项目需要配置打包方式为 pom -->
    <packaging>pom</packaging>
    <!-- 项目名称 -->
    <name>${project.artifactId}</name>
    <!-- 项目描述 -->
    <description>用户服务</description>
    <modules>
        <module>idle-store-user-api</module>
        <module>idle-store-user-biz</module>
    </modules>

</project>