spring:
  application:
    name: idle-store-commodity
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8087

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.lh.idlestore.commodity.repository.dataobject

cache:
  caffeine:
    enabled: true
    default-cache:
      maximum-size: 1000
      expire-after-write-seconds: 600
    caches:
      commodityCategoryList:
        maximum-size: 1
        expire-after-write-seconds: 1800

commodity:
  outbox:
    publish-delay: 1s
  cache:
    category:
      delayed-invalidation-delay: 3s

