<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lh</groupId>
        <artifactId>idle-store</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>idle-store-framework</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <modules>
        <module>idle-store-common</module>
        <module>idle-store-cache-contract</module>
        <module>lh-spring-boot-starter-biz-operationlog</module>
        <module>lh-spring-boot-starter-jackson</module>
        <module>lh-spring-boot-starter-redis</module>
        <module>lh-spring-boot-starter-biz-context</module>
        <module>lh-spring-boot-starter-web</module>
        <module>lh-spring-boot-starter-logging</module>
        <module>lh-spring-boot-starter-thread-pool</module>
        <module>lh-spring-boot-starter-openfeign</module>
    </modules>
</project>
