############## Sa-Token 配置 ##############
sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: random-128
  is-log: true
